language: node_js
node_js: 
  - 14
install:
  yarn && cd client yarn
jobs:
  include:
    - stage: "Tests"
      name: "Backend Tests"
      script: yarn run test
    - script: cd client && yarn test
      name: "FrontEnd Tests"